---
- name: debian_family | Install apt-transport-https
  apt:
    name: apt-transport-https
    state: latest
    update_cache: yes

- name: debian_family | Add gpg key of Docker repository
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
    validate_certs: False

- name: debian_family | Add Docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present

- name: debian_family | Install Docker Compose
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - docker-compose

- name: debian_family | Install Docker
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - docker-ce=5:24.0.7-1~ubuntu.20.04~focal
      - docker-ce-cli=5:24.0.7-1~ubuntu.20.04~focal
  notify:
    - start docker
